---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip3 install -r requirements.txt
  - ansible --version
  - molecule --version
script:
  - molecule lint
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
