---
- name: "debug vg"
  debug:
    var: vg
    verbosity: 2

- name: "debug lvm"
  loop: "{{ vg.lvnames | default([]) }}"
  debug:
    var: lv
    verbosity: 1
  loop_control:
    loop_var: lv

- name: manage_lvm | creating new LVM logical volume(s)
  lvol:
    vg: "{{ vg.vgname }}"
    lv: "{{ lv.lvname }}"
    size: "{{ lv.size }}"
    shrink: no
    opts: "{{ lv.opts | default('') }}"
    state: "present"
  loop: "{{ vg.lvnames | default([])  }}"
  loop_control:
    loop_var: lv
  become: true
  when: >
    (
    (vg.create is defined
    and vg.create) and
    (lv != 'None') and
    (lv.create is defined and
    lv.create)
    )
