---
- name: create_lv | Display Volume Group
  debug:
    var: vg
    verbosity: 2

- name: create_lv | debug lvm
  loop: "{{ vg.lvnames | default([]) }}"
  debug:
    var: lv
    verbosity: 1
  loop_control:
    loop_var: lv

- name: create_lv | creating new LVM logical volume(s)
  lvol:
    vg: "{{ vg.vgname }}"
    lv: "{{ lv.lvname }}"
    size: "{{ lv.size }}"
    shrink: false
    opts: "{{ lv.opts | default('') }}"
    state: present
  loop: "{{ vg.lvnames | default([])  }}"
  loop_control:
    loop_var: lv
  become: true
  when:
    - vg.create is defined
    - vg.create|bool
    - lv is defined
    - lv != 'None'
    - lv.create is defined
    - lv.create|bool
