---
- name: Converge
  hosts: all
  vars:
    lvm_groups:
      - vgname: my_vg
        disks:
          - /dev/sdb1
        create: true
        lvnames:
          - lvname: my_lv
            size: 40%VG
            opts: "--wipesignatures y"
            create: true
            filesystem: ext4
            mntp: "/var/lib/mountpoint"
          - lvname: my_lv2
            size: 10%VG
            opts: "--wipesignatures y"
            create: true
            filesystem: xfs
            mntp: "/var/lib/mountpoint2"
    manage_lvm: true

  tasks:
    - name: "Include lvm"
      include_role:
        name: "ansible-manage-lvm"
